### ISSUE TITLE
how to test this chatbot real time?

### ISSUE THREAD

**Issue by vssudarsan8** [karma9874/Seq2Seq-Chatbot#1]
hi , superb work ,how can we have a conversation with the chatbot?

**Comment by karma9874** [comment]
Thanks and yes we can have realtime conversation try this step https://github.com/karma9874/Seq2Seq-Chatbot#to-chat-with-the-trained-model-from-web-chat

**Comment by vssudarsan8** [comment]
I was running the .ipynb on colab, my ram is poor, can you help with real time conversation on colab

**Comment by karma9874** [comment]
Well you can check the cell 114 of that notebook, you just need to add it into while loop which can fulfill your requirement
